### ISSUE TITLE
It doesn't works in Linux Mint? (based on Debian and Ubuntu 22.04)

### ISSUE THREAD

**Issue by painkiller1717** [netslutter/ADB-Toolkit#1]
I used this tool in Parrot Security OS, which is really helpful and I like the features which it has, but want to know if isn't possible of any way to use in Linux Mint. I downloaded it with git clone, but when I tried to install, this is the error:

Argument used '-i'

Awk: Ord.:1 :1: Notice: The argument of the orders line «/etc/upstream-release» is directory: it jumps
THE DISTRO "ubuntu debian" IS NOT IDENTIFIED PLEASE MANUALLY INSTALL 'ADB' & 'FASTBOOT' FOR YOUR DISTRO.

I downloaded ADB and Fastboot without problems, I already have it, but same error still appears when I try to install with the file of installation. Isn't possible to use on Linux Mint? That would be nice.

 Thanks in advance, and great work!!

**Comment by netslutter** [comment]
> I used this tool in Parrot Security OS, which is really helpful and I like the features which it has, but want to know if isn't possible of any way to use in Linux Mint. I downloaded it with git clone, but when I tried to install, this is the error:
> 
> Argument used '-i'
> 
> Awk: Ord.:1 :1: Notice: The argument of the orders line «/etc/upstream-release» is directory: it jumps THE DISTRO "ubuntu debian" IS NOT IDENTIFIED PLEASE MANUALLY INSTALL 'ADB' & 'FASTBOOT' FOR YOUR DISTRO.
> 
> I downloaded ADB and Fastboot without problems, I already have it, but same error still appears when I try to install with the file of installation. Isn't possible to use on Linux Mint? That would be nice.
> 
> Thanks in advance, and great work!!

Sorry for your incontinence ! will update soon as possible
